// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: kv.sql

package sqlite

import (
	"context"
)

const getVal = `-- name: GetVal :one
SELECT
    val
FROM
    kv
WHERE
    key = ?
`

func (q *Queries) GetVal(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getVal, key)
	var val string
	err := row.Scan(&val)
	return val, err
}

const setVal = `-- name: SetVal :exec
INSERT OR REPLACE INTO kv (key, val)
VALUES
    (?, ?)
`

func (q *Queries) SetVal(ctx context.Context, key string, val string) error {
	_, err := q.db.ExecContext(ctx, setVal, key, val)
	return err
}
