// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlite

import (
	"database/sql"
)

type Hook struct {
	Name     string
	Script   sql.NullString
	IsFile   bool
	Filepath sql.NullString
}

type KeyHook struct {
	Key  string
	Hook string
}

type Kv struct {
	Key string
	Val string
}
