// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlite

import (
	"context"
)

type Querier interface {
	addFileHook(ctx context.Context, arg addFileHookParams) error
	addFilePathHook(ctx context.Context, arg addFilePathHookParams) error
	addScriptHook(ctx context.Context, arg addScriptHookParams) error
	attachHook(ctx context.Context, arg attachHookParams) error
	getAttachedHooks(ctx context.Context, key string) ([]Hook, error)
	getVal(ctx context.Context, key string) (string, error)
	hookExists(ctx context.Context, name string) (int64, error)
	keyExists(ctx context.Context, key string) (int64, error)
	listHooks(ctx context.Context) ([]string, error)
	listKeys(ctx context.Context) ([]string, error)
	setVal(ctx context.Context, arg setValParams) error
}

var _ Querier = (*Queries)(nil)
