// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlite

import (
	"context"
)

type Querier interface {
	attachHook(ctx context.Context, arg attachHookParams) error
	deleteHook(ctx context.Context, name string) error
	deleteKey(ctx context.Context, key string) error
	getAttachedHooks(ctx context.Context, key string) ([]Hook, error)
	getVal(ctx context.Context, key string) (string, error)
	hookExists(ctx context.Context, name string) (int64, error)
	keyExists(ctx context.Context, key string) (int64, error)
	listHooks(ctx context.Context) ([]string, error)
	listKeys(ctx context.Context) ([]string, error)
	setFileHook(ctx context.Context, arg setFileHookParams) error
	setFilePathHook(ctx context.Context, arg setFilePathHookParams) error
	setScriptHook(ctx context.Context, arg setScriptHookParams) error
	setVal(ctx context.Context, arg setValParams) error
}

var _ Querier = (*Queries)(nil)
